#!/usr/bin/env ruby

# This script parses the output of `:profile` and prints the results in
# descending order of self time.

require "debug"

file_path = "profile.log"
script = ""

Script = Data.define(:name, :time)

scripts = [].tap do |scripts|
  File.foreach(file_path) do |line|
    if line =~ /^SCRIPT\s+(\S+)/
      script = $1
    elsif line =~ /^ Self time:\s+(\S+)/
      self_time = $1
      scripts << Script.new(name: script, time: self_time.to_f)
    end
  end
end

scripts.sort_by(&:time).each do |script|
  puts "#{script.name} -- #{script.time}"
end
