-- DOCS: Sets up icons used everywhere else. These require a Nerd Font to be
-- installed. Find more and customize from here: https://www.nerdfonts.com/cheat-sheet

return {
  arrow_left = "",
  arrow_right = "",
  open = "",
  collapsed = "",
  target = "",
  bug = "",
  check = "",
  chevron_left = "",
  chevron_right = "",
  circle = "",
  code = "",
  copilot = "",
  cross = "",
  download = "",
  empty_circle = "",
  error = "",
  event = "",
  hint = "",
  fire = "󰈸",
  gear = "",
  ghost = "󰊠",
  import = "",
  info = "",
  keyboard = "",
  manup = "",
  package = "",
  pencil = "",
  performance = "󰡴",
  pause = "",
  play = "",
  running = "",
  skipped = "",
  question_mark = "",
  selected = "",
  source = "",
  square = "",
  telescope = "",
  test = "",
  text = "",
  vim = "",
  warn = "",
  x_mark = "✗",
  dap = {
    step_into = "",
    step_over = "",
    step_out = "",
    step_back = "",
    run_last = "",
    terminate = "",
  },
  git = {
    branch = "",
    added = "",
    modified = "",
    removed = "",
    renamed = "➜",
    untracked = "★",
    ignored = "◌",
    unstaged = "✗",
    staged = "✓",
    conflict = "",
  },
  separators = {
    top_left_wedge = "",
    left_semicircle = ""
  },
  folders = {
    closed = "",
    open = "",
    empty = "",
    default = "",
  },
  files = {
    find = "󰱼",
    new = "",
    code = "󰎧",
  },
  coding = {
    method = "m",
    func = "󰊕",
    constructor = "󰊐",
    field = "",
    variable = "󰫧",
    class = "",
    interface = "",
    module = "",
    property = "",
    unit = "",
    value = "",
    enum = "",
    keyword = "",
    snippet = "",
    color = "",
    reference = "",
    constant = "",
    struct = "",
    operator = "",
    type = "󰛦",
  }
}
