return {
  code = "",
  gear = "",
  event = "",
  manup = "",
  import = "",
  keyboard = "",
  check = "",
  ghost = "󰊠",
  package = "",
  vim = "",
  source = "",
  cross = "",
  play = "",
  circle = "",
  empty_circle = "",
  square = "",
  chevron_right = "",
  chevron_left = "",
  download = "",
  text = "",
  files = {
    find = "󰱼",
    new = "",
    code = "󰎧",
  },
}
