return {
  code = "",
  gear = "",
  event = "",
  files = "",
  manup = "",
  import = "",
  keyboard = "",
  check = "",
  ghost = "󰊠",
  package = "",
  vim = "",
  source = "",
  play = "",
  circle = "",
  empty_circle = "",
  square = "",
  chevron_right = "",
  chevron_left = "",
}
