-- Used keymaps to set keybinds
-- Used by whichkey to show keybinds on popup

-- Modes
--   normal_mode = "n",
--   insert_mode = "i",
--   visual_mode = "v",
--   visual_block_mode = "x",
--   term_mode = "t",
--   command_mode = "c",

return {
  {
    mode = "n",
    key = "<Leader>;",
    command = "<cmd>lua require'dap'.continue()<CR>",
    description = "Continue debugging",
  },
  {
    mode = "n",
    key = "<Leader><Leader>",
    command = "<C-^>",
    description = "Switch between the last two files",
  },
  {
    mode = "n",
    key = "<Leader>e",
    command = "<cmd>Neotree<CR>",
    description = "Open Neotree",
  },
  {
    mode = "n",
    key = "<C-p>",
    command = "<cmd>Telescope find_files<CR>",
    description = "Search files with Telescope using git-ls with fallback",
  },
  {
    mode = "n",
    key = "<C-\\>",
    command = "<cmd>Telescope frecency workspace=CWD<CR>",
    description = "Search frequently used files with Telescope using frecency",
  },
  {
    mode = "n",
    key = "<C-\\>",
    command = "<cmd>Telescope frecency workspace=CWD<CR>",
    description = "Search frequently used files with Telescope using frecency",
  },
  {
    mode = "n",
    key = "\\",
    command = "<cmd>Telescope live_grep<CR>",
    description = "Grep files with '\\'",
  },
  {
    mode = "n",
    key = "to",
    command = "<cmd>Telescope oldfiles<CR>",
    description = "View recently accessed files",
  },
  {
    mode = "n",
    key = "tmp",
    command = "<cmd>Telescope man_pages<CR>",
    description = "Find man pages",
  },
  {
    mode = "n",
    key = "thi",
    command = "<cmd>Telescope highlights<CR>",
    description = "Search through highlights",
  },
  {
    mode = "n",
    key = "tvo",
    command = "<cmd>Telescope vim_options<CR>",
    description = "Search through vim options",
  },
  {
    mode = "n",
    key = "the",
    command = "<cmd>Telescope help_tags<CR>",
    description = "Search through help tags in man pages",
  },
  {
    mode = "n",
    key = "tkm",
    command = "<cmd>Telescope keymaps<CR>",
    description = "Search through your keymaps",
  },
  {
    mode = "n",
    key = "tts",
    command = "<cmd>Telescope treesitter<CR>",
    description = "Navigate treesitter symbols in the current buffer",
  },
  {
    mode = "n",
    key = "td",
    command = "<cmd>Telescope diagnostics<CR>",
    description = "Navigate through current diagnostics",
  },
  {
    mode = "n",
    key = "tds",
    command = "<cmd>Telescope lsp_document_symbols<CR>",
    description = "Navigate through document symbols from LSP",
  },
  {
    mode = "n",
    key = "tm",
    command = "<cmd>Telescope marks<CR>",
    description = "Navigate through marks (bookmarks for page position with V key)",
  },
  {
    mode = "n",
    key = "<C-h>",
    command = "<C-w>h",
    description = "Better window navigation (left)",
  },
  {
    mode = "n",
    key = "<C-j>",
    command = "<C-w>j",
    description = "Better window navigation (down)",
  },
  {
    mode = "n",
    key = "<C-k>",
    command = "<C-w>k",
    description = "Better window navigation (up)",
  },
  {
    mode = "n",
    key = "<C-l>",
    command = "<C-w>l",
    description = "Better window navigation (right)",
  },
  {
    mode = "n",
    key = "<M-Up>",
    command = ":resize -2<CR>",
    description = "Resize window height (-2)",
  },
  {
    mode = "n",
    key = "<M-Down>",
    command = ":resize +2<CR>",
    description = "Resize window height (+2)",
  },
  {
    mode = "n",
    key = "<M-Left>",
    command = ":vertical resize +2<CR>",
    description = "Resize window width (+2)",
  },
  {
    mode = "n",
    key = "<M-Right>",
    command = ":vertical resize -2<CR>",
    description = "Resize window width (-2)",
  },
  {
    mode = "n",
    key = "<S-l>",
    command = ":bnext<CR>",
    description = "Navigate to next buffer",
  },
  {
    mode = "n",
    key = "<S-h>",
    command = ":bprevious<CR>",
    description = "Navigate to previous buffer",
  },
  {
    mode = "n",
    key = "<A-j>",
    command = "<Esc>:m .+1<CR>==gi",
    description = "Move text down",
  },
  {
    mode = "n",
    key = "<A-k>",
    command = "<Esc>:m .-2<CR>==gi",
    description = "Move text up",
  },
  {
    mode = "v",
    key = "<",
    command = "<gv",
    description = "Stay in indent mode (shift left)",
  },
  {
    mode = "v",
    key = ">",
    command = ">gv",
    description = "Stay in indent mode (shift right)",
  },
  {
    mode = "v",
    key = "<A-j>",
    command = ":m .+1<CR>==",
    description = "Move text down (visual)",
  },
  {
    mode = "v",
    key = "<A-k>",
    command = ":m .-2<CR>==",
    description = "Move text up (visual)",
  },
  {
    mode = "x",
    key = "J",
    command = ":move '>+1<CR>gv-gv",
    description = "Move visual block down",
  },
  {
    mode = "x",
    key = "K",
    command = ":move '<-2<CR>gv-gv",
    description = "Move visual block up",
  },
  {
    mode = "n",
    key = "<Leader>=",
    command = "<Cmd>vertical resize +10<CR>",
    description = "Increase window width by 10",
  },
  {
    mode = "n",
    key = "<Leader>-",
    command = "<Cmd>vertical resize -10<CR>",
    description = "Decrease window width by 10",
  },
  {
    mode = "n",
    key = "<leader>s",
    command = "<cmd>TestNearest<CR>",
    description = "Run nearest test",
  },
  {
    mode = "n",
    key = "<leader>t",
    command = "<cmd>TestFile<CR>",
    description = "Run current test file",
  },
  {
    mode = "n",
    key = "?",
    command = "<cmd>lua vim.diagnostic.open_float({max_height=400})<CR>",
    description = "Open diagnostic float window",
  },
  {
    mode = "n",
    key = "[d",
    command = "<cmd>lua vim.diagnostic.goto_prev()<CR>",
    description = "Go to previous diagnostic",
  },
  {
    mode = "n",
    key = "]d",
    command = "<cmd>lua vim.diagnostic.goto_next()<CR>",
    description = "Go to next diagnostic",
  },
  {
    mode = "n",
    key = "<leader>q",
    command = "<cmd>lua vim.diagnostic.setloclist()<CR>",
    description = "Set diagnostic list",
  },
  {
    mode = "n",
    key = "<leader>bd",
    command = "<cmd>lua require('bufdelete').bufdelete(0, true)<CR>",
    description = "Close buffer",
  },
}
