local M = {}

function M.setup(colors)
  return {
    Normal = { fg = colors.foreground },
    -- Normal text in non-current windows
    NormalNC = { link = "Normal" },
    NonText = { fg = colors.gray },
    Comment = { link = "NonText" },
    NormalFloat = { bg = colors.black },
    FloatBorder = { fg = colors.lightest_gray, bg = colors.black },
    FloatBorderDocs = { link = "FloatBorder" },
    Title = { fg = colors.blue },
    FloatTitle = { link = "Title" },
    FloatFooter = { link = "NonText" },
    FloatShadow = { link = "NonText" },
    FloatShadowThrough = { link = "NonText" },
    Background = { bg = colors.background },
    ColorColumn = { bg = colors.darker_gray },
    Conceal = { fg = colors.light_gray },
    Cursor = { fg = colors.black, bg = colors.foreground },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorLine = { bg = colors.darker_gray },
    CursorColumn = { link = "CursorLine" },
    TermCursor = { link = "Cursor" },
    TermCursorNC = { link = "Cursor" },
    Directory = { fg = colors.blue },
    Added = { fg = colors.green, bg = colors.black },
    DiffAdd = { link = "Added" },
    Removed = { fg = colors.red, bg = colors.black },
    DiffDelete = { link = "Removed" },
    Changed = { fg = colors.yellow, bg = colors.black },
    DiffChange = { link = "Changed" },
    DiffText = { fg = colors.lightest_gray, bg = colors.darker_gray },
    EndOfBuffer = { link = "NonText" },
    ErrorMsg = { fg = colors.red },
    WinSeparator = { fg = colors.background, bg = colors.background },
    VertSplit = { link = "WinSeparator" },
    Folded = { fg = colors.lightest_gray, bg = colors.darker_gray },
    FoldColumn = { fg = colors.gray, bg = colors.background },
    SignColumn = { fg = colors.lightest_gray, bg = colors.background },
    Search = { fg = colors.black, bg = colors.yellow },
    CurSearch = { fg = colors.black, bg = colors.blue },
    IncSearch = { link = "Search" },
    Substitute = { link = "Search" },
    LineNr = { fg = colors.light_gray },
    LineNrAbove = { link = "LineNr" },
    LineNrBelow = { link = "LineNr" },
    CursorLineNr = { bold = true },
    MatchParen = { bg = colors.gray },
    ModeMsg = { fg = colors.green },
    StatusLine = { link = "Background" },
    StatusLineNC = { link = "StatusLine" },
    MsgArea = { link = "StatusLine" },
    MsgSeparator = { link = "StatusLine" },
    MoreMsg = { fg = colors.blue },
    Pmenu = { link = "NormalFloat" },
    PmenuBorder = { link = "FloatBorder" },
    PmenuSel = { fg = colors.black, bg = colors.foreground },
    PmenuSbar = { bg = colors.dark_gray },
    PmenuKind = { fg = colors.blue },
    PmenuKindSel = { fg = colors.blue, bg = colors.lightest_gray },
    PmenuExtra = { fg = colors.purple },
    PmenuExtraSel = { fg = colors.purple, bg = colors.lightest_gray },
    -- Thumb of the scrollbar in the popup menu
    PmenuThumb = { bg = colors.gray },
    Question = { link = "MoreMsg" },
    QuickFixLine = { fg = colors.blue, bold = true },
    SpecialKey = { link = "NonText" },
    -- Word that is spelled wrong
    SpellBad = { fg = colors.red, undercurl = true, sp = colors.red },
    -- Word that should start with a capital
    SpellCap = { fg = colors.yellow, undercurl = true, sp = colors.yellow },
    -- Word that is recognized by the spell checker
    SpellLocal = { fg = colors.green, undercurl = true, sp = colors.green },
    -- Word that is recognized by the spell checker but is not in the current dictionary
    SpellRare = { fg = colors.purple, undercurl = true, sp = colors.purple },
    TabLine = { link = "StatusLine" },
    TabLineFill = { link = "TabLine" },
    TabLineSel = { fg = colors.foreground, bg = colors.black },
    Visual = { bg = colors.dark_gray },
    VisualNOS = { link = "Visual" },
    WarningMsg = { fg = colors.yellow },
    Whitespace = { link = "NonText" },
    WildMenu = { link = "Search" },
    WinBar = { link = "TabLine" },
    WinBarNC = { link = "TabLine" },
  }
end

return M
