local M = {}

function M.setup(colors)
  return {
    AlphaHeader = { link = "Title" },
    AlphaFooter = { fg = colors.yellow },

    DevIcon = { fg = colors.foreground },
    DevIconDefault = { link = "DevIcon" },
    DevIconLua = { fg = colors.blue },
    DevIconMarkdown = { link = "DevIconDefault" },
    DevIconLog = { link = "DevIconDefault" },
    DevIconConfiguration = { fg = colors.green },
    DevIconFolder = { fg = colors.blue },
    DevIconZsh = { fg = colors.green },
    DevIconRasi = { fg = colors.green },
    DevIconReadme = { link = "DevIconMarkdown" },
    DevIconMustache = { link = "DevIconConfiguration" },
    DevIconConfig = { link = "DevIconConfiguration" },
    DevIconConf = { link = "DevIconConfiguration" },
    DevIconIni = { link = "DevIconConfiguration" },
    DevIconSh = { fg = colors.red },
    DevIconTerminal = { link = "DevIconSh" },
    DevIcon7z = { fg = colors.orange },
    DevIconZip = { link = "DevIcon7z" },
    DevIconi3 = { fg = colors.blue },
    DevIconDb = { link = "DevIconDefault" },
    DevIconEx = { fg = colors.purple },
    DevIconGo = { fg = colors.cyan },
    DevIconGz = { fg = colors.orange },
    DevIconBin = { fg = colors.blue },
    DevIconWaveformAudioFile = { fg = colors.purple },
    DevIconMPEGAudioLayerIII = { fg = colors.purple },
    DevIconCss = { fg = colors.cyan },
    DevIconScss = { link = "DevIconCss" },
    DevIconCsv = { fg = colors.green },
    DevIconTmux = { link = "DevIconConfiguration" },
    DevIconZshrc = { link = "DevIconZsh" },
    DevIconTxt = { link = "DevIconDefault" },
    DevIconPrettierConfig = { link = "DevIconConfiguration" },
    DevIconNotebook = { fg = colors.yellow },
    DevIconDoc = { fg = colors.blue },
    DevIconDockerfile = { fg = colors.blue },
    DevIconDotenv = { link = "DevIconConfiguration" },
    DevIconEnv = { link = "DevIconConfiguration" },
    DevIconGif = { fg = colors.purple },
    DefIconJpg = { fg = colors.purple },
    DevIconJpegXl = { link = "DevIconJpg" },
    DevIconSvg = { link = "DevIconJpg" },
    DevIconWebp = { link = "DevIconJpg" },
    DevIconSolidity = { fg = colors.green },
    DevIconFavicon = { link = "DevIconJpg" },
    DevIconHtml = { fg = colors.orange },
    DevIconPdf = { fg = colors.red },
    DevIconIco = { link = "DevIconJpg" },
    DevIconImg = { link = "DevIconJpg" },
    DevIconImage = { link = "DevIconJpg" },
    DevIconInfo = { link = "DevIconDefault" },
    DevIconArch = { fg = colors.blue },
    DevIconAlpine = { fg = colors.blue },
    DevIconAppleScript = { link = "DevIconConfiguration" },
    DevIconApple = { fg = colors.blue },
    DevIconDebian = { fg = colors.blue },
    DevIconBash = { link = "DevIconSh" },
    DevIconBashProfile = { link = "DevIconSh" },
    DevIconEpub = { fg = colors.orange },
    DevIconEbook = { link = "DevIconEpub" },
    DevIconMobimb = { link = "DevIconEpub" },
    DevIconGIMP = { fg = colors.purple },
    DevIconPackageJson = { link = "DevIconConfiguration" },
    DevIconJson = { link = "DevIconConfiguration" },
    DevIconYml = { link = "DevIconConfiguration" },
    DevIconToml = { link = "DevIconConfiguration" },
    DevIconJson5 = { link = "DevIconConfiguration" },
    DevIconJsonc = { link = "DevIconConfiguration" },
    DevIconAstro = { fg = colors.blue },
    DevIconCMake = { fg = colors.gray },
    DevIconCrystal = { fg = colors.red },
    DevIconRuby = { fg = colors.red },
    DevIconGemfile = { link = "DevIconRuby" },
    DevIconRakefile = { link = "DevIconRuby" },
    DevIconBrewfile = { link = "DevIconRuby" },
    DevIconRb = { link = "DevIconRuby" },
    DevIconGemspec = { link = "DevIconRuby" },
    DevIconConfigRu = { link = "DevIconRuby" },
    DevIconGraphQL = { fg = colors.purple },
    DevIconDownload = { link = "DevIconDefault" },
    DevIconEslintrc = { fg = colors.cyan },
    DevIconJs = { fg = colors.cyan },
    DevIconJavascriptReactSpec = { link = "DevIconJs" },
    DevIconJavascriptReactTest = { link = "DevIconJs" },
    DevIconJsx = { link = "DevIconJs" },
    DevIconCjs = { link = "DevIconJs" },
    DevIconGDScript = { fg = colors.cyan },
    DevIconEdeavour = { fg = colors.blue },
    DevIconGitCommit = { fg = colors.orange },
    DevIconGitlabCI = { link = "DevIconGitCommit" },
    DevIconGitLogo = { link = "DevIconGitCommit" },
    DevIconGitConfig = { link = "DevIconConfiguration" },
    DevIconGitIgnore = { link = "DevIconGitCommit" },
    DevIconGitAttributes = { link = "DevIconGitCommit" },

    NeoTreeNormal = { link = "Background" },
    NeoTreeNormalNC = { link = "NeoTreeNormal" },
    NeoTreeNormalEndOfBuffer = { link = "NeoTreeNormal" },
    NeoTreeDimText = { link = "NonText" },
    NeoTreeFadeText1 = { link = "NeoTreeDimText" },
    NeoTreeFadeText2 = { link = "NeoTreeDimText" },
    NeoTreeWinSeparator = { link = "WinSeparator" },
    NeoTreeModified = { fg = colors.yellow },
    NeoTreeGitAdded = { link = "Added" },
    NeoTreeGitConflict = { link = "Removed" },
    NeoTreeGitUnstaged = { link = "Changed" },
    NeoTreeGitUntracked = { fg = colors.purple },
    NeoTreeTab = { link = "TabLine" },
    NeoTreeTabActive = { link = "TabLineSel" },
    NeoTreeTabInactive = { link = "TabLine" },
    NeoTreeSeparator = { link = "WinSeparator" },
    NeoTreeCursorLine = { link = "CursorLine" },

    BufferLineBackground = { link = "TabLine" },
    BufferLineSeparator = { link = "WinSeparator" },
    BufferLineTabSeparator = { link = "WinSeparator" },
    BufferLineFill = { link = "TabLine" },
    BufferLineTab = { link = "TabLine" },
    BufferLineBufferSelected = {
      fg = colors.foreground,
      bg = colors.background,
      bold = true,
    },
    BufferLineBufferTabSelected = { link = "BufferLineBufferSelected" },
    BufferLineCloseButton = { fg = colors.red },
    BufferLineCloseButtonVisible = { link = "BufferLineCloseButton" },
    BufferLineCloseButtonSelected = { link = "BufferLineCloseButton" },
    BufferLineBufferVisible = { link = "BufferLineBufferSelected" },
    BufferLineDevIconDefault = { link = "DevIconDefault" },

    IlluminatedWordText = { link = "DiffText" },
    IlluminatedWordRead = { link = "IlluminatedWordText" },
    IlluminatedWordWrite = { link = "IlluminatedWordText" },

    NeotestPassed = { fg = colors.green },
    NeotestFailed = { fg = colors.red },
    NeotestSkipped = { fg = colors.orange },
    NeotestRunning = { fg = colors.yellow },
    NeotestNamespace = { fg = colors.purple },
    NeotestFile = { link = "Directory" },
    NeotestDirectory = { link = "Directory" },

    SatelliteBar = { bg = colors.dark_gray },
    SatelliteBackground = { link = "Background" },

    TelescopeTitle = { link = "Title" },
    TelescopeMatching = { fg = colors.yellow, bold = true },
    TelescopeBorder = { link = "FloatBorder" },
    TelescopeSelection = { fg = colors.lightest_gray, bold = true },
    TelescopeMultiSelection = { link = "TelescopeSelection" },

    barbecue_normal = { link = "Background" },

    NotifyBackground = { link = "Background" },
    NotifyBody = { link = "Normal" },
    NotifyERRORBorder = { fg = colors.red, bg = colors.background },
    NotifyERRORBody = { link = "NotifyBody" },
    NotifyERRORTitle = { fg = colors.red, bg = colors.background, bold = true },
    NotifyERRORIcon = { fg = colors.red },
    NotifyWARNBorder = { fg = colors.yellow, bg = colors.background },
    NotifyWARNBody = { link = "NotifyBody" },
    NotifyWARNIcon = { fg = colors.yellow },
    NotifyWARNTitle = {
      fg = colors.yellow,
      bg = colors.background,
      bold = true,
    },
    NotifyINFOBorder = { fg = colors.blue, bg = colors.background },
    NotifyINFOBody = { link = "NotifyBody" },
    NotifyINFOTitle = { fg = colors.blue, bg = colors.background, bold = true },
    NotifyINFOIcon = { fg = colors.blue },
    NotifyDEBUGBorder = { fg = colors.purple, bg = colors.background },
    NOtifyDEBUGBody = { link = "NotifyBody" },
    NotifyDEBUGTitle = {
      fg = colors.purple,
      bg = colors.background,
      bold = true,
    },
    NotifyDEBUGIcon = { fg = colors.purple },
    NotifyHINTBorder = { fg = colors.purple, bg = colors.background },
    NotifyHINTBody = { link = "NotifyBody" },
    NotifyHINTTitle = {
      fg = colors.purple,
      bg = colors.background,
      bold = true,
    },
    NotifyHINTIcon = { fg = colors.purple },
    NotifyOKBorder = { fg = colors.green, bg = colors.background },
    NotifyOKBody = { link = "NotifyBody" },
    NotifyOKTitle = { fg = colors.green, bg = colors.background, bold = true },
    NotifyOKIcon = { fg = colors.green },

    GitSignsAdd = { link = "Added" },
    GitSignsAddNr = { link = "GitSignsAdd" },
    GitSignsChange = { link = "Changed" },
    GitSignsChangeNr = { link = "GitSignsChange" },
    GitSignsDelete = { link = "Removed" },
    GitSignsDeleteNr = { link = "GitSignsDelete" },

    MiniClueBorder = { link = "FloatBorder" },
    MiniClueDescGroup = { link = "DiagnosticWarn" },
    MiniClueDescSingle = { link = "NormalFloat" },
    MiniClueNextKey = { link = "DiagnosticHint" },
    MiniClueNextKeyWithPostkeys = { link = "DiagnosticOk" },
    MiniClueSeparator = { link = "NonText" },
    MiniClueTitle = { link = "Title" },
    MiniSurround = { link = "IncSearch" },

    SnacksIndent = { link = "NonText" },
    SnacksIndentScope = { fg = colors.foreground },
    SnacksIndentChunk = { link = "SnacksIndentScope" },
    SnacksIndent1 = { link = "SnacksIndentScope" },
    SnacksIndent2 = { link = "SnacksIndentScope" },
    SnacksIndent3 = { link = "SnacksIndentScope" },
    SnacksIndent4 = { link = "SnacksIndentScope" },
    SnacksIndent5 = { link = "SnacksIndentScope" },
    SnacksIndent6 = { link = "SnacksIndentScope" },
    SnacksIndent7 = { link = "SnacksIndentScope" },
    SnacksIndent8 = { link = "SnacksIndentScope" },

    NoiceCmdlinePopupBorder = { fg = colors.blue },
    NoiceConfirmBorder = { fg = colors.purple },

    LazyButton = { bg = colors.darker_gray },
    LazyButtonActive = { bg = colors.dark_gray },
    LazyDimmed = { link = "Comment" },
    LazyH1 = { bg = colors.dark_gray },

    TroubleCount = { fg = colors.green, bold = true },
    TroubleFoldIcon = { fg = colors.lighter_Gray },
    TroubleIndent = { fg = colors.dark_gray },
    TroubleLocation = { fg = colors.light_gray },
    TroubleSignError = { link = "DiagnosticError" },
    TroubleSignHint = { link = "DiagnosticHint" },
    TroubleSignInformation = { link = "DiagnosticInfo" },
    TroubleSignOther = { link = "DiagnosticInfo" },
    TroubleSignWarning = { link = "DiagnosticWarn" },
    TroubleText = { fg = colors.lighter_gray },
    TroubleTextError = { link = "TroubleText" },
    TroubleTextHint = { link = "TroubleText" },
    TroubleTextInformation = { link = "TroubleText" },
    TroubleTextWarning = { link = "TroubleText" },

    CmpPmenu = { link = "Pmenu" },
    CmpItemAbbr = { fg = colors.lighter_gray },
    CmpItemAbbrDeprecated = { fg = colors.gray },
    CmpItemAbbrMatch = { fg = colors.yellow },
    CmpItemAbbrMatchFuzzy = { fg = colors.yellow },
    CmpItemKind = { fg = colors.magenta, bg = colors.darker_gray },
    CmpItemMenu = { fg = colors.lighter_gray, bg = colors.darker_gray },
    CmpItemKindClass = { link = "Type" },
    CmpItemKindColor = { link = "Special" },
    CmpItemKindConstant = { link = "Constant" },
    CmpItemKindConstructor = { link = "Type" },
    CmpItemKindEnum = { link = "Structure" },
    CmpItemKindEnumMember = { link = "Structure" },
    CmpItemKindEvent = { link = "Exception" },
    CmpItemKindField = { link = "Structure" },
    CmpItemKindFile = { link = "Tag" },
    CmpItemKindFolder = { link = "Directory" },
    CmpItemKindFunction = { link = "Function" },
    CmpItemKindInterface = { link = "Structure" },
    CmpItemKindKeyword = { link = "Identifier" },
    CmpItemKindMethod = { link = "Method" },
    CmpItemKindModule = { link = "Structure" },
    CmpItemKindOperator = { link = "Operator" },
    CmpItemKindProperty = { link = "Structure" },
    CmpItemKindReference = { link = "Tag" },
    CmpItemKindSnippet = { link = "Special" },
    CmpItemKindStruct = { link = "Structure" },
    CmpItemKindText = { link = "Statement" },
    CmpItemKindTypeParameter = { link = "Type" },
    CmpItemKindUnit = { link = "Special" },
    CmpItemKindValue = { link = "Identifier" },
    CmpItemKindVariable = { link = "Delimiter" },
    FloatBorderCmp = { link = "FloatBorder" },

    IndentBlanklineChar = { fg = colors.dark_gray, nocombine = true },
    IndentBlanklineContextChar = { fg = colors.magenta, nocombine = true },
    IndentBlanklineContextStart = {
      sp = colors.magenta,
      underline = true,
      nocombine = true,
    },
    IndentBlanklineIndent1 = { fg = colors.green },
    IndentBlanklineIndent2 = { fg = colors.blue },
    IndentBlanklineIndent3 = { fg = colors.yellow },
    IndentBlanklineIndent4 = { fg = colors.orange },
    IndentBlanklineIndent5 = { fg = colors.purple },
    IndentBlanklineIndent6 = { fg = colors.red },
    IndentBlanklineIndent7 = { fg = colors.cyan },
    IndentBlanklineIndent8 = { fg = colors.magenta },

    DapUIScope = { link = "Title" },
    DapUIType = { link = "Type" },
    DapUIModifiedValue = { fg = colors.purple, bold = true },
    DapUIDecoration = { link = "Title" },
    DapUIThread = { link = "String" },
    DapUIStoppedThread = { link = "Title" },
    DapUISource = { link = "Directory" },
    DapUILineNumber = { link = "Title" },
    DapUIFloatBorder = { link = "FloatBorder" },
    DapUIWatchesEmpty = { link = "ErrorMsg" },
    DapUIWatchesValue = { link = "String" },
    DapUIWatchesError = { link = "DiagnosticError" },
    DapUIBreakpointsPath = { link = "Directory" },
    DapUIBreakpointsInfo = { link = "DiagnosticInfo" },
    DapUIBreakpointsCurrentLine = { fg = colors.green, bold = true },
    DapUIBreakpointsDisabledLine = { link = "Comment" },
    DapStoppedLine = { link = "CursorLine" },

    MasonError = { link = "ErrorMsg" },
    MasonHeader = { fg = colors.black, bg = colors.blue },
    MasonHeaderSecondary = { fg = colors.black, bg = colors.magenta },
    MasonHeading = { bold = true },
    MasonHighlight = { fg = colors.magenta },
    MasonHighlightBlock = { fg = colors.black, bg = colors.magenta },
    MasonHighlightBlockBold = { link = "MasonHeaderSecondary" },
    MasonHighlightBlockBoldSecondary = { link = "MasonHeader" },
    MasonHighlightBlockSecondary = { fg = colors.black, bg = colors.blue },
    MasonLink = { link = "MasonHighlight" },
    MasonMuted = { link = "Comment" },
    MasonMutedBlock = { fg = colors.black, bg = colors.gray },
    MasonMutedBlockBold = { fg = colors.black, bg = colors.gray, bold = true },
  }
end

return M
