#!/bin/sh

# https://wiki.manjaro.org/index.php?title=Proper_~/.xinitrc_File
# https://wiki.archlinux.org/title/Xinit

# Our configs inside our dotfiles
userresources=$XDG_CONFIG_HOME/.Xresources
usermodmap=$XDG_CONFIG_HOME/.Xmodmap

# The base system configs
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
  xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
  xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# Swap escape and capslock
setxkbmap -option 'caps:swapescape'

# Increase the keyboard repeat rate
xset r rate 300 50

# Set environment variables if needed
# export DISPLAY=:0

# Start background programs if necessary (optional)
# Example: start a background compositor or input method
# picom &

# Execute i3 as the window manager
exec i3
