#!/bin/zsh

# Post-up script for after running `rcup`

touch "$HOME"/.psqlrc.local

# Set default branch to master
if [ -f "$HOME/.git_template/HEAD" ] && \
  [ "$(cat "$HOME/.git_template/HEAD")" = "ref: refs/heads/master" ]; then
  echo "Removing ~/.git_template/HEAD in favor of defaultBranch" >&2
  rm -f ~/.git_template/HEAD
fi

# detect old OS X broken /etc/zshenv and suggest rename
if grep -qw path_helper /etc/zshenv 2>/dev/null; then
  dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)

  cat <<MSG >&2
Warning: \`/etc/zshenv' configuration file on your system may cause unexpected
PATH changes on subsequent invocations of the zsh shell. The solution is to
rename the file to \`zprofile':
  sudo mv /etc/{zshenv,zprofile}

(called from ${dir}/post-up:${LINENO})

MSG
fi

# Function to check the operating system
get_os() {
  os_name=$(uname -s)
  case "$os_name" in
    Linux*)     echo "Linux";;
    Darwin*)    echo "macOS";;
    *)          echo "Unknown";;
  esac
}

os=$(get_os)
echo "Operating System: $os"

# Check if the OS variable is set correctly
if [[ -z "$os" ]]; then
  echo "Failed to determine the operating system."
  exit 1
fi

# Function to check if a command exists
check_command() {
  command_name=$1

  if ! command -v $command_name &> /dev/null; then
    if [[ "$os" == "macOS" ]]; then
      echo "Warning: $command_name is not installed. Please install it with \`brew install $command_name\`" >&2
    elif [[ "$os" == "Linux" ]]; then
      echo "Warning: $command_name is not installed. Please install it with \`paru -S $command_name\` or \`yay -S $command_name\`" >&2
    else
      echo "Warning: $command_name is not installed. Please install it" >&2
    fi
  fi
}

# List of required commands
required_commands=("bat" "eza")

# Check each required command
echo "Checking for dependencies that need installing..."

for cmd in $required_commands; do
  check_command $cmd
done
